In [1]:
import numpy as np
import xarray as xr
import zarr as zr
from matplotlib import pyplot as plt

In [18]:
dataset = xr.open_zarr('example_simulation.zarr')
dataset = dataset.isel(time=slice(0, 1))
dataset

<xarray.Dataset> Size: 1MB
Dimensions:               (time: 1, baseline_id: 351, uvw_label: 3,
                           frequency: 256, baseline_antenna1_id: 351,
                           baseline_antenna2_id: 351, polarization: 1)
Coordinates:
  * baseline_antenna1_id  (baseline_antenna1_id) int32 1kB 0 0 0 0 ... 24 24 25
  * baseline_antenna2_id  (baseline_antenna2_id) int32 1kB 1 2 3 4 ... 25 26 26
  * baseline_id           (baseline_id) int32 1kB 0 1 2 3 4 ... 347 348 349 350
  * frequency             (frequency) float64 2kB 2.998e+08 ... 3.091e+08
  * polarization          (polarization) <U1 4B 'I'
  * time                  (time) float64 8B 1.715e+09
  * uvw_label             (uvw_label) <U1 12B 'u' 'v' 'w'
Data variables:
    UVW                   (time, baseline_id, uvw_label) float64 8kB dask.array<chunksize=(1, 176, 2), meta=np.ndarray>
    VISIBILITY            (time, baseline_id, frequency) complex128 1MB dask.array<chunksize=(1, 44, 32), meta=np.ndarray>
Attributes:
    creation_date:  2024-05-09T07:00:00+00:00.000
    intent:         Example Simulation
    version:        0.0.1

In [7]:
image_size = 2048 # Size of image in pixels
c = 299792458 # Speed of light
theta = 0.0125 # Size of image on sky, directional cosines
# Allocate array for gridded visibilities
gridded = np.zeros((image_size, image_size), dtype=complex)

time stamp 0, all baselines

In [80]:
uvw_bl = dataset.UVW[0].compute().to_numpy()
vis_bl = dataset.VISIBILITY[0].compute().to_numpy()
# these freqs are all the same 256 numbers for all baselines at all timestamps
freq = dataset.frequency.compute().to_numpy()

In [47]:
uvw_bl[0]

array([-916.7084, -618.3884,    0.    ])

In [48]:
vis_bl[0]

array([-225.37576834-1732.92237004j, -220.52933174-1732.76528258j,
       -215.53751072-1732.59458787j, -210.69606587-1732.40653779j,
       -205.71009365-1732.20393996j, -200.98854972-1731.99496455j,
       -196.00887035-1731.7609014j , -191.17849327-1731.5115093j ,
       -186.20532869-1731.24570682j, -181.38091793-1730.96559199j,
       -176.41460272-1730.66813525j, -171.59648384-1730.35738144j,
       -166.78145598-1730.03157837j, -161.82585031-1729.68704996j,
       -157.01759977-1729.33073615j, -152.06967582-1728.95477333j,
       -147.2685271 -1728.56803675j, -142.44435372-1728.1748598j ,
       -137.65071301-1727.75812976j, -132.71923218-1727.31992239j,
       -127.93333671-1726.87294943j, -123.01053073-1726.40358532j,
       -118.23270347-1725.92646241j, -113.31890367-1725.42603794j,
       -108.54946702-1724.91885975j, -103.7841557 -1724.39692423j,
        -98.88427984-1723.85033582j,  -94.12783949-1723.29848939j,
        -89.23779311-1722.72108833j,  -84.60713173-1722.157635

In [134]:
freq_bl = np.tile(freq, (len(uvw_bl), 1))
freq_bl

array([[2.99792458e+08, 2.99829054e+08, 2.99865650e+08, ...,
        3.09051185e+08, 3.09087781e+08, 3.09124377e+08],
       [2.99792458e+08, 2.99829054e+08, 2.99865650e+08, ...,
        3.09051185e+08, 3.09087781e+08, 3.09124377e+08],
       [2.99792458e+08, 2.99829054e+08, 2.99865650e+08, ...,
        3.09051185e+08, 3.09087781e+08, 3.09124377e+08],
       ...,
       [2.99792458e+08, 2.99829054e+08, 2.99865650e+08, ...,
        3.09051185e+08, 3.09087781e+08, 3.09124377e+08],
       [2.99792458e+08, 2.99829054e+08, 2.99865650e+08, ...,
        3.09051185e+08, 3.09087781e+08, 3.09124377e+08],
       [2.99792458e+08, 2.99829054e+08, 2.99865650e+08, ...,
        3.09051185e+08, 3.09087781e+08, 3.09124377e+08]])

In [1]:
from mpi4py import MPI

[darkstar:512787] shmem: mmap: an error occurred while determining whether or not /tmp/ompi.darkstar.1000/jf.0/3966042112/shared_mem_cuda_pool.darkstar could be created.
[darkstar:512787] create_and_attach: unable to create shared memory BTL coordinating structure :: size 134217728 


In [9]:
%px
comm = MPI.COMM_WORLD
size = comm.Get_size()
rank = comm.Get_rank()
PID = os.getpid()

UsageError: Line magic function `%px` not found.


In [6]:
import os


In [7]:
print(f'rank: {rank} has PID: {PID}')

rank: 0 has PID: 512787


In [10]:
dataset = dataset.isel(time=slice(0, 1))
dataset = dataset.isel(time=slice(0, 1))


NameError: name 'dataset' is not defined